steps:
  # Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-483711/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
    options:
      logging: CLOUD_LOGGING_ONLY
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'us-east4-docker.pkg.dev/sleepr-483711/reservations/production']
    options:
      logging: CLOUD_LOGGING_ONLY

  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-483711/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
    options:
      logging: CLOUD_LOGGING_ONLY
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/sleepr-483711/auth/production']
    options:
      logging: CLOUD_LOGGING_ONLY

  # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-483711/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
    options:
      logging: CLOUD_LOGGING_ONLY
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'us-east4-docker.pkg.dev/sleepr-483711/notifications/production']
    options:
      logging: CLOUD_LOGGING_ONLY

  # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-483711/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ] 
    options:
      logging: CLOUD_LOGGING_ONLY
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/sleepr-483711/payments/production']
    options:
      logging: CLOUD_LOGGING_ONLY